#
#  release.yml
#  LearnCHANGELOG
#
#  Created by west on 30/11/25.
#

name: Release Changelog

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
        # Lokasi file configurasi
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
         
        # Branch target
          target-branch: ${{ github.ref_name }}
          
        # Token untuk membuat PR dan release
          token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Tampilkan output untuk debugging
      - name: Show Release Output
        if: steps.release.outputs.release_created
        run: |
            echo "Release created: ${{ steps.release.ouputs.release_created }}"
            echo "Tag name: ${{ steps.release.outputs.tag_name }}"
            echo "Version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
            echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
